import type { Metadata } from "next";
import Link from "next/link";
import { socialMetadata } from "@/lib/seo";

const title = "Why saint dates and feast calendars differ";
const description = "Understand recurring saint commemorations, liturgical rank, local calendars, and the celebration assigned in a particular year.";
export const metadata: Metadata = { title, description, alternates: { canonical: "/editorial-policy/feast-calendars" }, ...socialMetadata(title, description, "/editorial-policy/feast-calendars") };

export default function FeastCalendars() {
  return <main className="reading-page">
    <p className="eyebrow mb-3">Using the directory</p>
    <h1 className="text-4xl md:text-5xl font-heading mb-6">Why saint dates and feast calendars differ</h1>
    <div className="text-cream-dark leading-relaxed space-y-8">
      <p>A biography gives a recurring date associated with a saint. That is useful for finding a life to read, but it is not a complete instruction about which Mass your parish celebrates. Start with the biography’s calendar note, then check the approved calendar for your community and the year concerned.</p>
      <section><h2 className="text-2xl text-cream mb-3">A commemoration is not always a liturgical feast</h2><p>Our date label is “Commemoration.” In ordinary speech, people often call any saint’s anniversary a feast day. An approved liturgical calendar also specifies a rank: solemnity, feast, memorial, or optional memorial. A traditional saint-directory listing does not, by itself, establish that rank or require celebration everywhere.</p><p className="mt-3"><Link className="text-link" href="/saints/mary-magdalene#evidence">Mary Magdalene’s July 22 celebration</Link> was raised from memorial to feast in 2016. The date stayed the same. <a className="text-link" href="https://press.vatican.va/content/salastampa/en/bollettino/pubblico/2016/06/10/160610c.html">Read the Holy See’s explanation.</a></p><p className="mt-3"><Link className="text-link" href="/saints/john-paul-ii#evidence">John Paul II’s October 22 celebration</Link> is an optional memorial. His example shows why a saint’s liturgical date need not be the anniversary of death. <a className="text-link" href="https://www.usccb.org/prayer-and-worship/liturgical-year-and-calendar/saint-john-paul-ii">See the USCCB’s liturgical entry.</a></p></section>
      <section><h2 className="text-2xl text-cream mb-3">Check which calendar a source is describing</h2><p>The General Roman Calendar and calendars particular to a country, diocese, or religious community serve different scopes. A local connection can explain why one community gives a saint a prominence absent from a general directory. The <a className="text-link" href="https://www.usccb.org/resources/2026cal.pdf">USCCB’s 2026 calendar introduction</a> directs diocesan calendar makers to add local dedications and particular saints’ commemorations.</p><p className="mt-3">For the United States, the <a className="text-link" href="https://www.usccb.org/committees/divine-worship/liturgical-calendar">USCCB’s annual calendar</a> combines the General Roman Calendar with the U.S. proper calendar and identifies each day’s celebration and rank. Use the edition for the year concerned rather than assuming an older edition reflects later additions.</p></section>
      <section><h2 className="text-2xl text-cream mb-3">Keep the recurring date and this year’s observance separate</h2><p>The seasonal calendar and other celebrations affect what is observed in a particular year. Check the current local calendar or parish notice instead of applying an automatic transfer rule to every saint. Older sources may preserve a date from an earlier calendar. When sources differ, record their date, edition, and geographic or religious scope before deciding that either source is wrong.</p><p className="mt-3">A date written in another calendar system also needs its calendar identified. A Julian date and its civil Gregorian equivalent should not be presented as an unexplained pair of competing feast days. Ask which calendar the community follows before converting a date.</p></section>
      <section><h2 className="text-2xl text-cream mb-3">How to use Saint of the Day</h2><p><Link className="text-link" href="/saint-of-day">Saint of the Day</Link> selects a saint for reading from the directory’s dated commemorations. Some dates draw on local calendars or historical commemorations, explained in their notes. It does not replace the liturgical calendar or the readings assigned to your parish’s Mass.</p><p className="mt-3">If you find a discrepancy, send the page URL and the relevant calendar edition or diocesan source to <a className="text-link" href="mailto:hello@saintdiscoveryquiz.com?subject=Saint%20calendar%20correction">hello@saintdiscoveryquiz.com</a>. A calendar qualification can be as useful as changing the date itself.</p></section>
      <p className="text-sm">Prepared with AI-assisted source comparison on October 3, 2026. This guide is not an official liturgical ruling.</p>
      <p><Link className="text-link" href="/editorial-policy">Editorial approach →</Link> · <Link className="text-link" href="/editorial-policy/corrections">Corrections log →</Link></p>
    </div>
  </main>;
}
