import patronageData from "@/lib/data/patronage.json";

// Generated by scripts/build-patronage.mjs from patron_of in saints.json.
export interface PatronTopic {
  slug: string;
  label: string;
  saints: string[];
}

export interface PatronLink {
  slug: string;
  label: string;
}

const data = patronageData as {
  topics: PatronTopic[];
  bySaint: Record<string, PatronLink[]>;
};

export const PATRON_TOPICS: PatronTopic[] = data.topics;

const TOPIC_BY_SLUG = new Map(data.topics.map((t) => [t.slug, t]));

export function getTopicBySlug(slug: string): PatronTopic | null {
  return TOPIC_BY_SLUG.get(slug) ?? null;
}

export function getPatronLinksForSaint(saintSlug: string): PatronLink[] {
  return data.bySaint[saintSlug] ?? [];
}

const SMALL_WORDS = new Set([
  "of", "the", "and", "in", "for", "a", "an", "to", "with", "from", "against",
]);

// "the sick" -> "the Sick" (first word keeps its article casing when small),
// existing capitals (England, HIV/AIDS, St. Petersburg) are preserved.
export function titleCaseLabel(label: string): string {
  return label
    .split(" ")
    .map((word, i) =>
      SMALL_WORDS.has(word.toLowerCase()) && i > 0
        ? word.toLowerCase()
        : word.charAt(0).toUpperCase() + word.slice(1)
    )
    .join(" ");
}

// Catholic convention: patronage "against pestilence" reads
// "Patron Saint Against Pestilence", everything else "Patron Saint(s) of X".
export function topicTitle(topic: PatronTopic): string {
  const plural = topic.saints.length > 1 ? "Patron Saints" : "Patron Saint";
  if (topic.label.toLowerCase().startsWith("against ")) {
    return `${plural} Against ${titleCaseLabel(topic.label.slice(8))}`;
  }
  return `${plural} of ${titleCaseLabel(topic.label)}`;
}
