import patronageData from "@/lib/data/patronage.json";
import { canonicalSaintSlug, getBiographyReview } from "@/lib/saint-reviews";

// Generated by scripts/build-patronage.mjs from patron_of in saints.json.
export interface PatronTopic {
  slug: string;
  label: string;
  saints: string[];
}

export interface PatronLink {
  slug: string;
  label: string;
}

const data = patronageData as {
  topics: PatronTopic[];
  bySaint: Record<string, PatronLink[]>;
};

// A corrected biography must not retain unsupported claims through the old
// generated patronage index. Unreviewed records remain pending independently.
export const PATRON_TOPICS: PatronTopic[] = data.topics.map(topic => ({
  ...topic,
  saints: [...new Set(topic.saints.map(canonicalSaintSlug))].filter(slug => {
    const review = getBiographyReview(slug);
    if (!review) return true;
    return (review.patron_of ?? "").split(/[,;]/)
      .some(label => label.trim().toLowerCase() === topic.label.toLowerCase());
  }),
})).filter(topic => topic.saints.length > 0);

const TOPIC_BY_SLUG = new Map(PATRON_TOPICS.map((t) => [t.slug, t]));

export function getTopicBySlug(slug: string): PatronTopic | null {
  return TOPIC_BY_SLUG.get(slug) ?? null;
}

export function getPatronLinksForSaint(saintSlug: string): PatronLink[] {
  return PATRON_TOPICS.filter(topic => topic.saints.includes(canonicalSaintSlug(saintSlug)))
    .map(({ slug, label }) => ({ slug, label }));
}

const SMALL_WORDS = new Set([
  "of", "the", "and", "in", "for", "a", "an", "to", "with", "from", "against",
]);

// "the sick" -> "the Sick" (first word keeps its article casing when small),
// existing capitals (England, HIV/AIDS, St. Petersburg) are preserved.
export function titleCaseLabel(label: string): string {
  return label
    .split(" ")
    .map((word, i) =>
      SMALL_WORDS.has(word.toLowerCase()) && i > 0
        ? word.toLowerCase()
        : word.charAt(0).toUpperCase() + word.slice(1)
    )
    .join(" ");
}

// Catholic convention: patronage "against pestilence" reads
// "Patron Saint Against Pestilence", everything else "Patron Saint(s) of X".
export function topicTitle(topic: PatronTopic): string {
  const plural = topic.saints.length > 1 ? "Patron Saints" : "Patron Saint";
  if (topic.label.toLowerCase().startsWith("against ")) {
    return `${plural} Against ${titleCaseLabel(topic.label.slice(8))}`;
  }
  return `${plural} of ${titleCaseLabel(topic.label)}`;
}
